name       : hunspell-pl
version    : 20190101
release    : 4
source     :
    - https://solus-project.com/sources/hunspell/sjp-myspell-pl-20190101.zip : f951c78bbcb6725d5b8a15e1930f62c17c63a44399a45412cbd805e888121328
license    : Apache-2.0
component  : spelling
summary    : Polish hunspell dictionaries
description: |
    Polish hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -D -d -m 00755 $installdir/usr/share/hunspell
    unzip pl_PL.zip
    install -m 00644 pl_PL.dic pl_PL.aff $installdir/usr/share/hunspell/
