name       : hunspell-pl
version    : 20160720
release    : 1
source     :
    - http://sjp.pl/slownik/ort/sjp-myspell-pl-20160720.zip : 56210a9a7f59267fd2f0684ec940f6e3abc1800a0fb59e4793c32845e6d9cdd8
license    : MPL-2.0
component  : spelling
summary    : Polish hunspell dictionaries
description: |
    Polish hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -d -m 00644 $installdir/usr/share/hunspell
    unzip pl_PL.zip
    install -m 00644 pl_PL.dic pl_PL.aff $installdir/usr/share/hunspell/