name       : hunspell-pl
version    : 20160803
release    : 2
source     :
    - http://sjp.pl/slownik/ort/sjp-myspell-pl-20160803.zip : d7014f92fdd498ea7060ad89f37482bc16469478340deed95dbd5d01da233af2
license    : MPL-2.0
component  : spelling
summary    : Polish hunspell dictionaries
description: |
    Polish hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -D -d -m 00755 $installdir/usr/share/hunspell
    unzip pl_PL.zip
    install -m 00644 pl_PL.dic pl_PL.aff $installdir/usr/share/hunspell/
