name       : hunspell-pl
version    : 20190104
release    : 6
source     :
    - https://getsol.us/sources/hunspell/sjp-myspell-pl-20190104.zip : 65907c4fe0baa6b7af3de81fc2f43f7fde74e7e52ca9ada6849f6974801f17d5
license    : Apache-2.0
component  : office.spelling
summary    : Polish hunspell dictionaries
description: |
    Polish hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -Ddm00755 $installdir/usr/share/hunspell
    unzip pl_PL.zip
    install -m00644 pl_PL.dic pl_PL.aff $installdir/usr/share/hunspell/
